name: Publish Docker images

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ['7.16.2']
    env:
      repo: "govpf/elasticsearch"
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get build date
      id: build-date
      run: |
        echo "::set-output name=BUILD_DATE::$(date +"%Y-%m-%dT%H:%M:%S.%NZ")"

    - name: Build and push
      uses: docker/build-push-action@v6.0.0
      with:
        context: ./7
        file: ./7/Dockerfile
        platforms: linux/amd64
        build-args: |
          ELASTIC_VERSION=${{ matrix.versions }}
          BUILD_DATE=${{ steps.build-date.outputs.BUILD_DATE }}
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v4.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"
